### ISSUE TITLE
Add RSS/Atom

### ISSUE THREAD

**Issue by dngray** [d3npa/universe#2]
Supporting RSS/Atom is a necessary feature for a blog.

If you're like me and read a tonne of different blogs you're going to be using a RSS client otherwise you won't know when something new is posted.

Just hoping that a user will decide to "bookmark" your site isn't enough.

the `<link rel="alternate"/>` attribute should appear in the top of your source so that auto discovery can work.

**Comment by d3npa** [comment]
Hey, thanks for your suggestion!
I have no idea why but I never got an alert. Anyways I'm sorry for the delay.
That sounds like a great idea! I'll research into how RSS works and how I can support it.
P.S. privacytools.io rocks! :) thank you for the great work.

**Comment by d3npa** [comment]
I've intergrated some RSS support in the most recent commits. 
I've never implemented RSS before, so there may be unexpected issues with it. 
Please feel free to reach out if you find any. \(^^)/
